kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.5.0",
            "id": "buuk8s-super-fun-demo",
            "label": "http",
            "remark": "A1 Template",
            "AS3-http": {
                "class": "Tenant",
                "A1": {
                    "class": "Application",
                    "template": "generic",
                    "buus_aks_k8s_demo": {
                        "class": "Service_HTTP",
                        "remark": "hello world demo",
                        "virtualAddresses": [
                            "10.0.2.10"
                        ],
                        "pool": "web_pool"
                    },
                    "web_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }            
                }
            }
        }
    }